apiVersion: v1
kind: Service
metadata:
  name: reactdemosvc
  labels:
    app: react
    region: in
spec:
  selector:
    matchLabels:
      app: react
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
