apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactdemo
  labels:
    app: react
    region: in
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: reactdemo
          image: moqaddas/reactdemo:latest
          ports:
            - protocol: TCP
              containerPort: 80
